#pragma once

#include "types.h"

static const f32 CAMERA_ZOOM_MINIMUM = 1.0f;
static const int CIRCLE_SEGMENT_COUNT = 16;
static const f32 FONT_SIZE = 13.0f;
static const f32 GIMMICK_SQUARE_SIZE = 1.2f;
static const f32 COMMON_GIMMICK_SQUARE_SIZE = 1.2f;
static const f32 WALL_POINT_SIZE = .4f;

// colors

static const u32 COLOR_STAGE_BOUNDS             = 0x808080FF;
static const u32 COLOR_WALL_ACTIVE              = 0xFFFFFFFF;
static const u32 COLOR_WALL_INACTIVE            = 0xFFFFFF7F;
static const u32 COLOR_WALL_LABEL_ACTIVE        = 0xADD8E6FF;
static const u32 COLOR_WALL_LABEL_INACTIVE      = 0xADD8E67F;
static const u32 COLOR_GIMMICK_COMMON_ACTIVE    = 0xB191FFFF;
static const u32 COLOR_GIMMICK_COMMON_INACTIVE  = 0xB191FF7F;
static const u32 COLOR_GIMMICK_UNIQUE_ACTIVE    = 0x2B59C3FF;
static const u32 COLOR_GIMMICK_UNIQUE_INACTIVE  = 0x2B59C37F;
static const u32 COLOR_PATH_ACTIVE              = 0xB2FF9EFF;
static const u32 COLOR_PATH_INACTIVE            = 0xB2FF9E7F;
static const u32 COLOR_ZONE_ACTIVE              = 0xFF8CC6FF;
static const u32 COLOR_ZONE_INACTIVE            = 0xFF8CC67F;
static const u32 COLOR_RACE_COURSE_INFO_ACTIVE  = 0x00FFFFFF;
static const u32 COLOR_RACE_COURSE_INFO_INACTIVE= 0x00FFFF7F;
static const u32 COLOR_ENEMY_ACTIVE             = 0xFF0000FF;
static const u32 COLOR_ENEMY_INACTIVE           = 0xFF00007F;


// static const RGBA WALL_LINE_COLOR = 0xFFFFFFFF;
// static const RGBA WALL_POINT_HEAD_COLOR_ACTIVE = 0xEE4266FF;
// static const RGBA WALL_POINT_HEAD_COLOR_INACTIVE = 0xEE42667F;
// static const RGBA WALL_POINT_BODY_COLOR_ACTIVE = 0xF07167FF;
// static const RGBA WALL_POINT_BODY_COLOR_INACTIVE = 0xF071677F;


// static const RGBA LABELED_WALL_LINE_COLOR = 0xFF91A0FF;
// static const RGBA LABELED_WALL_POINT_HEAD_COLOR_ACTIVE = 0xC04CFDFF;
// static const RGBA LABELED_WALL_POINT_HEAD_COLOR_INACTIVE = 0xC04CFD7F;
// static const RGBA LABELED_WALL_POINT_BODY_COLOR_ACTIVE = 0xD99AC5FF;
// static const RGBA LABELED_WALL_POINT_BODY_COLOR_INACTIVE = 0xD99AC57F;


// static const RGBA COMMON_GIMMICK_COLOR_ACTIVE = 0x01BAEFFF;
// static const RGBA COMMON_GIMMICK_COLOR_INACTIVE = 0x01BAEF7F;

// static const RGBA GIMMICK_COLOR_ACTIVE		= 0x20BF55FF;
// static const RGBA GIMMICK_COLOR_INACTIVE	= 0x20BF557F;

// static const RGBA PATH_BODY_COLOR = 0xCBFF4DFF;
// static const RGBA PATH_POINT_COLOR_ACTIVE = 0x84DD63FF;
// static const RGBA PATH_POINT_COLOR_INACTIVE = 0x84DD637F;

// static const RGBA ZONE_COLOR_ACTIVE = 0xFFBA08FF;
// static const RGBA ZONE_COLOR_INACTIVE = 0xFFBA087F;