#pragma once

#include "types.h"

static const f32 CAMERA_ZOOM_MINIMUM = 1.0f;
static const int CIRCLE_SEGMENT_COUNT = 16;
static const f32 FONT_SIZE = 13.0f;
static const f32 GIMMICK_SQUARE_SIZE = 1.2f;
static const f32 COMMON_GIMMICK_SQUARE_SIZE = 1.2f;
static const f32 WALL_POINT_SIZE = 0.3f;

// colors

static const RGBA WALL_LINE_COLOR = 0xFFFFFFFF;
static const RGBA WALL_POINT_HEAD_COLOR_ACTIVE = 0xEE4266FF;
static const RGBA WALL_POINT_HEAD_COLOR_INACTIVE = 0xEE42667F;
static const RGBA WALL_POINT_BODY_COLOR_ACTIVE = 0xF07167FF;
static const RGBA WALL_POINT_BODY_COLOR_INACTIVE = 0xF071677F;

static const RGBA WALL2_LINE_COLOR = 0xFF91A0FF;
static const RGBA WALL2_POINT_HEAD_COLOR_ACTIVE = 0xC04CFDFF;
static const RGBA WALL2_POINT_HEAD_COLOR_INACTIVE = 0xC04CFD7F;
static const RGBA WALL2_POINT_BODY_COLOR_ACTIVE = 0xD99AC5FF;
static const RGBA WALL2_POINT_BODY_COLOR_INACTIVE = 0xD99AC57F;


static const RGBA COMMON_GIMMICK_COLOR_ACTIVE = 0x01BAEFFF;
static const RGBA COMMON_GIMMICK_COLOR_INACTIVE = 0x01BAEF7F;

static const RGBA GIMMICK_COLOR_ACTIVE		= 0x20BF55FF;
static const RGBA GIMMICK_COLOR_INACTIVE	= 0x20BF557F;

static const RGBA ZONE_COLOR_ACTIVE = 0xFFBA08FF;
static const RGBA ZONE_COLOR_INACTIVE = 0xFFBA087F;